#!/usr/bin/env php
<?php

declare(strict_types=1);

use SlamPsql\Psql;

require __DIR__.'/src/PsqlInterface.php';

require __DIR__.'/src/Psql.php';

$psql = Psql::fromGetopt(
    Psql::getopt(),
    ['PGPASSWORD' => (string) getenv('PGPASSWORD')],
    \STDOUT,
);
if (null === $psql) {
    exit(1);
}

$return = $psql->run(\STDIN, \STDOUT, \STDERR);

exit((int) (true !== $return));
