name: "CI"

on:
  pull_request:
  push:
    branches:
      - "master"
      - "renovate/*"

env:
  INI_VALUES: zend.assertions=1,error_reporting=-1

jobs:
  composer-json-lint:
    name: "Lint composer.json"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.2"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ env.INI_VALUES }}"
          tools: composer-normalize,composer-require-checker,composer-unused
      - uses: "ramsey/composer-install@v2"

      - run: "composer validate --strict"
      - run: "composer-normalize --dry-run"
      - run: "composer-require-checker check --config-file=$(realpath composer-require-checker.json)"
      - run: "composer-unused"

  tests:
    name: "Tests"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.3"
        code-coverage:
          - "none"
        include:
            - php-version: "8.2"
              code-coverage: "pcov"

    services:
      psql:
        image: postgres:latest
        env:
          POSTGRES_PASSWORD: 'root_password'
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: "actions/checkout@v4"
      - uses: "shivammathur/setup-php@v2"
        with:
          coverage: "${{ matrix.code-coverage }}"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ env.INI_VALUES }}"
      - uses: "ramsey/composer-install@v2"

      - name: "Wait for PostgreSQL to be ready"
        run: |
          until echo '' | PGPASSWORD=root_password psql --host=127.0.0.1 --port=5432 --username=postgres &> /dev/null
          do
            printf "."
            sleep 1
          done
        timeout-minutes: 1

      - run: "vendor/bin/phpunit --no-coverage --no-logging"
        if: ${{ matrix.code-coverage == 'none' }}
        timeout-minutes: 1

      - run: "vendor/bin/phpunit --coverage-clover=coverage.xml --no-logging"
        if: ${{ matrix.code-coverage != 'none' }}
        timeout-minutes: 1

      - name: "Send code coverage report to Codecov.io"
        if: ${{ matrix.code-coverage != 'none' }}
        uses: codecov/codecov-action@v4.3.0
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: true

  coding-standards:
    name: "Coding Standards"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.2"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ env.INI_VALUES }}"
      - uses: "ramsey/composer-install@v2"

      - run: "vendor/bin/php-cs-fixer fix --verbose --dry-run --diff"

  static-analysis:
    name: "Static Analysis"
    runs-on: "ubuntu-latest"
    strategy:
      matrix:
        php-version:
          - "8.2"

    steps:
      - uses: "actions/checkout@v4"
      - uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "${{ matrix.php-version }}"
          ini-values: "${{ env.INI_VALUES }}"
      - uses: "ramsey/composer-install@v2"

      - run: "vendor/bin/phpstan analyse --no-progress --error-format=github"
